esphome:
  name: bedroom-switch
  friendly_name: Bedroom Switch

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom-Switch Fallback Hotspot"
    password: "yMBf8F4uOxfI"

time:
  - platform: homeassistant
    id: homeassistant_time

      
spi:
  clk_pin: GPIO19  
  mosi_pin: GPIO23 
  miso_pin: GPIO25 

i2c:
  sda: GPIO4
  scl: GPIO0

psram: # Enable PSRAM Needed for 2025.2 onwards
  mode: octal
  speed: 80MHz

display:
  - platform: ili9xxx
    model: ST7789V
    cs_pin: GPIO22
    dc_pin: GPIO21
    reset_pin: GPIO18
    invert_colors: false
    auto_clear_enabled: false
    update_interval: never
    show_test_card: true 
    id: disp
    rotation: 180

output:
  - platform: ledc
    pin: GPIO5
    id: backlight_pwm
  - platform: ledc
    id: mood_red
    pin: GPIO26
  - platform: ledc
    id: mood_green
    pin: GPIO32
  - platform: ledc
    id: mood_blue
    pin: GPIO33        

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: backlight
    restore_mode: ALWAYS_ON
  - platform: rgb
    name: "Moodlight"
    red: mood_red
    green: mood_green
    blue: mood_blue

touchscreen:
  platform: ft63x6
  id: touch
  display: disp
  calibration:
    x_min: 0
    y_min: 0
    x_max: 230
    y_max: 312

  on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.x,
              touch.y,
              touch.x_raw,
              touch.y_raw
              );
  on_release:
    - if:
        condition: lvgl.is_paused
        then:
          - logger.log: "LVGL resuming"
          - lvgl.resume:
          - lvgl.widget.redraw:
          - light.turn_on: backlight
lvgl:
  displays:
    - disp
  default_font: montserrat_24
  on_idle:
    timeout: !lambda "return (id(display_timeout).state * 1000);"
    then:
      - logger.log: "LVGL is idle"
      - light.turn_off: backlight
      - lvgl.pause:

#time: !lambda "return  id(homeassistant_time).now();"
  style_definitions:
    - id: header_footer
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: COVER
      border_opa: TRANSP
      radius: 0
      pad_all: 0
      pad_row: 0
      pad_column: 0
      border_color: 0x0077b3
      text_color: 0xFFFFFF
      width: 100%
      height: 30
      text_font: montserrat_18
  pages:
    - id: main_page
      widgets:
        - obj:
            align: TOP_MID
            styles: header_footer
            widgets:
              - label:
                  text: "Bedroom"
                  align: CENTER
                  text_align: CENTER
                  text_color: 0xFFFFFF  
                  id: head_label

        - buttonmatrix:
            x: 5
            y: 40
            width: 235
            height: 200
            items:
              pressed:
                bg_color: 0x0f1e2f
              bg_color: 0xa3e8ff
            id: matrix_id
            rows:
              - buttons:
                - id: light_btn
                  control:
                    checkable: true
                  text: 'Lights'
                  on_click:
                    - homeassistant.action:
                        action: light.toggle
                        data:
                          entity_id: light.bedroom_lights
                    - logger.log:
                        format: "Button pressed"
              - buttons:
                - id: light2_btn
                  control:
                    checkable: true
                  text: 'Bed Light'
                  on_click:
                    - homeassistant.action:
                        action: light.toggle
                        data:
                          entity_id: light.brilliant_gu10_rgbw
                    - logger.log:
                        format: "bedhead Button pressed"
              - buttons:
                - id: aircon_btn
                  control:
                    checkable: true
                  text: 'Aircon'
                  on_click:
                    - homeassistant.action:
                        action: switch.toggle
                        data:
                          entity_id: switch.0200000b34c2_ac_power_status
                    - logger.log:
                        format: "aircon button pressed"                      




                                    



switch:
  - platform: gpio
    pin: GPIO12
    name: relay1
    id: relay1
  - platform: gpio
    pin: GPIO14
    name: relay2
    id: relay2
  - platform: gpio
    pin: GPIO27
    name: relay3
    id: relay3




binary_sensor:
  - platform: homeassistant
    id: bedroom_light
    entity_id: light.bedroom_lights
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: light_btn
          state:
            checked: !lambda return x;
  - platform: homeassistant
    id: bedhead_light
    entity_id: light.brilliant_gu10_rgbw
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: light2_btn
          state:
            checked: !lambda return x;            
  - platform: homeassistant
    id: bedroom_aircon
    entity_id: switch.0200000b34c2_ac_power_status
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: aircon_btn
          state:
            checked: !lambda return x;            
  - platform: lvgl
    name: button2
    widget: light_btn
    publish_initial_state: true
  - platform: lvgl
    name: button4
    widget: aircon_btn
    publish_initial_state: true    
  - platform: lvgl
    name: button3
    widget: light2_btn
    publish_initial_state: true
  - platform: status
    name: Status sensor

number:
  - platform: template
    name: LVGL Screen timeout
    optimistic: true
    id: display_timeout
    unit_of_measurement: "s"
    initial_value: 45
    restore_value: true
    min_value: 10
    max_value: 180
    step: 5
    mode: box

captive_portal:


